services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - social-pg-data:/var/lib/postgresql/data:Z
      - ./scripts:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

volumes:
  social-pg-data:
